services:
  mongo:
    image: mongo:7.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: akira
      MONGO_INITDB_ROOT_PASSWORD: akira
    ports:
      - 27017:27017
  redis:
    image: redis:7.4.0-alpine3.20
    ports:
      - 6379:6379
